#!/bin/bash
echo 'Extract the contents to ~/.local/share/cinnamon/search_providers'

echo 'Running import command:   

gsettings set org.cinnamon enabled-search-providers [\"search@timjae\"]

'

gsettings set org.cinnamon enabled-search-providers [\"search@timjae\"]

echo 'Restart Cinnamon with Ctrl+Alt+Esc'

